# Generated by Django 5.1.1 on 2024-10-01 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bitterness',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Bitterness must be at least 1'), django.core.validators.MaxValueValidator(10, 'Bitterness cannot exceed 10')]),
        ),
    ]
