# Generated by Django 5.1.1 on 2024-10-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_bitterness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BEV', 'Beverage'), ('BNS', 'Beans')], default='BEV', max_length=3),
        ),
    ]
